authors = ["<oss@fastly.com>"]
description = ""
language = "rust"
manifest_version = 3
name = "Geo-IP API at the edge"

[scripts]
  build = "cargo build --bin fastly-compute-project --release --target wasm32-wasi --color always"

[local_server.backends.origin_0]
      url = "https://http-me.glitch.me"

[setup.backends.origin_0]
address = "http-me.glitch.me"
port = 443
